name: Generate Doxygen Documentation

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/src/**'
      - 'frontend/src/**'
      - 'tools/**'
      - 'Doxyfile'
  push:
    branches: [ main ]
    paths:
      - 'backend/src/**'
      - 'frontend/src/**'
      - 'tools/**'
      - 'Doxyfile'
  workflow_dispatch:  # Allow manual trigger

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for proper versioning

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
          python3 \
          doxygen \
          graphviz

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: docs/html/
        retention-days: 30
